name = "notion-queue-worker"
main = "worker/notion-queue-worker.js"
compatibility_date = "2024-03-26"

kv_namespaces = [
  { binding = "NOTION_QUEUE_KV", id = "KV_NAMESPACE_ID" }
]

[triggers]
crons = ["*/5 * * * *"]
