# wrangler.toml - Конфигурация для Cloudflare Pages
name = "notion-review-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Настройки производительности
[limits] 
cpu_ms = 60000

# Привязка KV Namespace
[[kv_namespaces]]
binding = "KV-NOTION"  						# Имя переменной в коде
preview_id = "3f1037b3b7b1455daa8d60423d528092"  					# Ваш Namespace ID
id = "3f1037b3b7b1455daa8d60423d528092"          	# Ваш Namespace ID

# Переменные окружения (при необходимости)
[vars]
ENVIRONMENT = "production"