# wrangler.toml - ИСПРАВЛЕННАЯ конфигурация для Cloudflare Pages
name = "specnaz-forms"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Настройки производительности
[limits] 
cpu_ms = 60000

# Переменные окружения
[vars]
ENVIRONMENT = "production"

